import { Report } from './types';

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-001',
    trackingCode: 'TRC-2026-0812',
    title: 'Lubang Aspal Menganga Sangat Berbahaya untuk Pemotor',
    description: 'Terdapat lubang sedalam sekitar 15 cm di lajur kiri dekat lampu merah. Sudah ada 2 pengendara motor yang hampir terjatuh saat hujan malam hari.',
    category: 'jalan',
    status: 'pending',
    urgency: 'tinggi',
    latitude: -3.8210,
    longitude: 102.2780,
    address: 'Jl. Pariwisata Pantai Panjang (Dekat Jembatan Pasir Putih)',
    district: 'Ratu Samban',
    village: 'Lempuing',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #4102',
    reporterPhoneMasked: '0812****8821',
    reporterNikMasked: '1771**********03',
    createdAt: '2026-09-28T09:30:00Z',
    updatedAt: '2026-09-28T09:30:00Z',
    upvotes: 24,
    timeline: [
      {
        id: 'tl-1',
        date: '28 Sep 2026, 09:30',
        status: 'pending',
        title: 'Laporan Diterima Sistem',
        note: 'Laporan masuk dari warga terverifikasi NIK & OTP. Menunggu peninjauan petugas verifikator.',
        actor: 'Sistem TRACE',
      },
    ],
  },
  {
    id: 'rep-002',
    trackingCode: 'TRC-2026-0795',
    title: '3 Titik Lampu Jalan PJU Padam Total, Jalanan Sangat Gelap',
    description: 'Penerangan jalan umum di sepanjang lorong perumahan sudah mati selama 4 hari berturut-turut. Rawan kejahatan dan membahayakan warga pejalan kaki.',
    category: 'pju',
    status: 'in_progress',
    urgency: 'sedang',
    latitude: -3.7925,
    longitude: 102.2642,
    address: 'Jl. Soeprapto No. 45 (Sekitar Simpang Lima Ratu Samban)',
    district: 'Ratu Samban',
    village: 'Belakang Pondok',
    imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #1984',
    reporterPhoneMasked: '0857****3319',
    reporterNikMasked: '1771**********22',
    createdAt: '2026-09-27T19:15:00Z',
    updatedAt: '2026-09-28T14:20:00Z',
    upvotes: 18,
    assignedAgency: 'Dinas Perhubungan & Penerangan Jalan Kota Bengkulu',
    adminNote: 'Tim teknis PJU Rayon Kota telah dijadwalkan mengganti trafo dan lampu LED pada shift malam.',
    timeline: [
      {
        id: 'tl-2a',
        date: '27 Sep 2026, 19:15',
        status: 'pending',
        title: 'Laporan Masuk',
        note: 'Laporan diverifikasi oleh Admin TRACE.',
        actor: 'Admin Wilayah',
      },
      {
        id: 'tl-2b',
        date: '28 Sep 2026, 14:20',
        status: 'in_progress',
        title: 'Disposisi ke Tim Lapangan',
        note: 'Diteruskan ke Unit Penerangan Jalan Dinas Perhubungan. Regu 3 meluncur ke lokasi.',
        actor: 'Dishub Kota Bengkulu',
      },
    ],
  },
  {
    id: 'rep-003',
    trackingCode: 'TRC-2026-0780',
    title: 'Tumpukan Sampah Liar Menumpuk di Lahan Kosong Tepi Jalan',
    description: 'Banyak oknum membuang sampah rumah tangga dan puing bangunan secara liar hingga meluber ke tepi bahu jalan dan menimbulkan bau tidak sedap.',
    category: 'sampah',
    status: 'in_progress',
    urgency: 'sedang',
    latitude: -3.8015,
    longitude: 102.3020,
    address: 'Jl. Danau No. 12 (Tepi Danau Dendam Tak Sudah)',
    district: 'Singaran Pati',
    village: 'Dusun Besar',
    imageUrl: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #8812',
    reporterPhoneMasked: '0813****9012',
    reporterNikMasked: '1771**********55',
    createdAt: '2026-09-26T11:00:00Z',
    updatedAt: '2026-09-27T10:00:00Z',
    upvotes: 32,
    assignedAgency: 'Dinas Lingkungan Hidup (DLH) Kota Bengkulu',
    timeline: [
      {
        id: 'tl-3a',
        date: '26 Sep 2026, 11:00',
        status: 'pending',
        title: 'Laporan Terverifikasi',
        note: 'Laporan tumpukan sampah liar divalidasi kebenarannya.',
        actor: 'Admin DLH',
      },
      {
        id: 'tl-3b',
        date: '27 Sep 2026, 10:00',
        status: 'in_progress',
        title: 'Pengerahan Truk Pengangkut',
        note: 'Truk armada oranye DLH dijadwalkan angkut sampah pagi hari.',
        actor: 'Seksi Kebersihan DLH',
      },
    ],
  },
  {
    id: 'rep-004',
    trackingCode: 'TRC-2026-0752',
    title: 'Drainase Tersumbat Menimbulkan Banjir Genangan 40 cm',
    description: 'Saluran air utama mampet karena sampah dan endapan lumpur, air meluap ke badan jalan setiap kali turun hujan deras selama lebih dari 30 menit.',
    category: 'banjir',
    status: 'pending',
    urgency: 'darurat',
    latitude: -3.7680,
    longitude: 102.2790,
    address: 'Jl. Kalimantan No. 28 (Kawasan Rawa Makmur)',
    district: 'Muara Bangkahulu',
    village: 'Rawa Makmur',
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #5521',
    reporterPhoneMasked: '0819****1102',
    reporterNikMasked: '1771**********78',
    createdAt: '2026-09-29T06:45:00Z',
    updatedAt: '2026-09-29T06:45:00Z',
    upvotes: 45,
    timeline: [
      {
        id: 'tl-4',
        date: '29 Sep 2026, 06:45',
        status: 'pending',
        title: 'Laporan Darurat Masuk',
        note: 'Laporan genangan air mendesak masuk ke sistem.',
        actor: 'Sistem TRACE',
      },
    ],
  },
  {
    id: 'rep-005',
    trackingCode: 'TRC-2026-0689',
    title: 'Pembuangan Cairan Limbah Gelap Berbau ke Saluran Umum',
    description: 'Terlihat pipa buangan mengalirkan air keruh berminyak dan berbusa yang menyengat hidung di dekat kawasan saluran muara.',
    category: 'limbah',
    status: 'pending',
    urgency: 'tinggi',
    latitude: -3.8420,
    longitude: 102.2980,
    address: 'Kawasan Muara Sungai Jenggalu (Dekat Hutan Mangrove)',
    district: 'Gading Cempaka',
    village: 'Lingkar Barat',
    imageUrl: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #7743',
    reporterPhoneMasked: '0852****9941',
    reporterNikMasked: '1771**********90',
    createdAt: '2026-09-28T16:00:00Z',
    updatedAt: '2026-09-28T16:00:00Z',
    upvotes: 29,
    timeline: [
      {
        id: 'tl-5',
        date: '28 Sep 2026, 16:00',
        status: 'pending',
        title: 'Laporan Pencemaran Didaftarkan',
        note: 'Menunggu pengecekan sampel oleh Pejabat Pengawas Lingkungan Hidup (PPLH).',
        actor: 'Admin TRACE',
      },
    ],
  },
  {
    id: 'rep-006',
    trackingCode: 'TRC-2026-0610',
    title: 'Penutup Saluran Besi Trotoar Rusak dan Terbuka Lebar',
    description: 'Tutup manhole besi trotoar patah, meninggalkan celah sedalam 2 meter yang rawan mencelakai pejalan kaki difabel dan anak sekolah.',
    category: 'fasilitas',
    status: 'resolved',
    urgency: 'tinggi',
    latitude: -3.7872,
    longitude: 102.2515,
    address: 'Trotoar Depan Kawasan Wisata Benteng Marlborough',
    district: 'Teluk Segara',
    village: 'Kebun Keling',
    imageUrl: 'https://images.unsplash.com/photo-1584463699042-3a525164d9f6?auto=format&fit=crop&w=800&q=80',
    resolvedImageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #2041',
    reporterPhoneMasked: '0811****4040',
    reporterNikMasked: '1771**********41',
    createdAt: '2026-09-22T08:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
    upvotes: 56,
    assignedAgency: 'Dinas Bina Marga Provinsi',
    adminNote: 'Manhole besi cor baru telah dipasang kembali dengan pengunci anti-pencurian.',
    timeline: [
      {
        id: 'tl-6a',
        date: '22 Sep 2026, 08:00',
        status: 'pending',
        title: 'Laporan Diterima',
        note: 'Laporan lubang trotoar masuk antrean verifikasi.',
        actor: 'Sistem TRACE',
      },
      {
        id: 'tl-6b',
        date: '23 Sep 2026, 10:15',
        status: 'in_progress',
        title: 'Pemasangan Barikade Pengaman',
        note: 'Tim reaksi cepat memasang rambu pembatas sementara.',
        actor: 'Satgas Bina Marga',
      },
      {
        id: 'tl-6c',
        date: '25 Sep 2026, 11:00',
        status: 'resolved',
        title: 'Perbaikan Tuntas & Selesai',
        note: 'Penutup manhole standar baru selesai dipasang rapi dan aman.',
        actor: 'Dinas Bina Marga',
        evidenceUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?auto=format&fit=crop&w=800&q=80',
      },
    ],
  },
  {
    id: 'rep-007',
    trackingCode: 'TRC-2026-0830',
    title: 'Trotoar Amblas & Paving Rusak Dekat Lampu Jalan',
    description: 'Paving block trotoar amblas sedalam 20 cm, berjarak sekitar 50 meter dari lampu PJU yang padam. Membahayakan pejalan kaki di malam hari.',
    category: 'jalan',
    status: 'pending',
    urgency: 'sedang',
    latitude: -3.7929,
    longitude: 102.2645,
    address: 'Jl. Soeprapto No. 52 (Depan Pertokoan, Sekitar Simpang Lima)',
    district: 'Ratu Samban',
    village: 'Belakang Pondok',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    reporterAlias: 'Warga #3310',
    reporterPhoneMasked: '0812****7788',
    reporterNikMasked: '1771**********89',
    createdAt: '2026-09-29T10:15:00Z',
    updatedAt: '2026-09-29T10:15:00Z',
    upvotes: 14,
    timeline: [
      {
        id: 'tl-7',
        date: '29 Sep 2026, 10:15',
        status: 'pending',
        title: 'Laporan Diterima Sistem',
        note: 'Laporan trotoar amblas masuk antrean verifikasi petugas.',
        actor: 'Sistem TRACE',
      },
    ],
  },
];
